export enum SlideView {
    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    FORGOT_PASSWORD = 'FORGOT_PASSWORD',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    CREATE_QUIZ_FORM = 'CREATE_QUIZ_FORM',
    EDIT_QUIZ_FORM = 'EDIT_QUIZ_FORM',
    LEADER_BOARD = 'LEADER_BOARD'

}